const fs = require('fs');
const path = require('path');
const ejs = require('ejs');

const templatesDir = path.join(__dirname, 'templates');
const outputFilePath = path.join(__dirname, 'compiled-templates.js');

console.log('Starting EJS precompilation for Cloudflare Workers...');

const compiledFns = {};

function walkSync(dir, filelist = []) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const filepath = path.join(dir, file);
        if (fs.statSync(filepath).isDirectory()) {
            walkSync(filepath, filelist);
        } else if (file.endsWith('.ejs')) {
            filelist.push(filepath);
        }
    }
    return filelist;
}

try {
    const ejsFiles = walkSync(templatesDir);
    
    for (const file of ejsFiles) {
        const content = fs.readFileSync(file, 'utf8');
        // Get relative path without .ejs extension, normalized with forward slashes
        const relPath = path.relative(templatesDir, file).replace(/\\/g, '/').replace('.ejs', '');
        
        try {
            // Compile with client: true returns a function string
            const fnStr = ejs.compile(content, { client: true, compileDebug: false }).toString();
            compiledFns[relPath] = fnStr;
            console.log(`✓ Compiled: ${relPath}`);
        } catch (compileErr) {
            console.error(`❌ Error compiling ${relPath}:`, compileErr.message);
            process.exit(1);
        }
    }

    let jsOutput = `// AUTO-GENERATED FILE. DO NOT EDIT.\n`;
    jsOutput += `// Generated by build-ejs.js for Cloudflare Workers deployment\n\n`;
    jsOutput += `module.exports = {\n`;
    
    for (const [name, fnStr] of Object.entries(compiledFns)) {
        jsOutput += `  "${name}": ${fnStr},\n`;
    }
    
    jsOutput += `};\n`;

    fs.writeFileSync(outputFilePath, jsOutput, 'utf8');
    console.log(`\n🎉 Successfully precompiled ${Object.keys(compiledFns).length} templates to ${path.basename(outputFilePath)}`);
} catch (err) {
    console.error('Fatal error during precompilation:', err);
    process.exit(1);
}
