name = "dtracks"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./frontend"

[define]
"process.env.CLOUDFLARE_WORKER" = "true"

[vars]