name = "etracks"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./frontend"

[vars]
CLOUDFLARE_WORKER = "true"
NODE_ENV = "production"